import React from 'react';
import Header from './Header';
import Head from 'next/head'
import { Container } from 'semantic-ui-react';

export default (props) => {
	return (
		<Container>
			<Head>
				<title>Spectrum Auction</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			{props.children}

		</Container>
	);
}
